# Generated by Django 3.0 on 2020-07-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0002_etiket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiket',
            old_name='adi',
            new_name='etiket1',
        ),
        migrations.AddField(
            model_name='etiket',
            name='etiket2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
